### ISSUE TITLE
AdvancedLivePortraitPHM: "src_images" does not support "src" !

### ISSUE THREAD

**Issue by w1xmovies** [vinavfx/ComfyUI-Gizmos-for-Nuke#1]
When I hit submit on LIVEPORTRAIT gizmo, I do get this Nuke error.

AdvancedLivePortraitPHM: "src_images" does not support "src" !

Also I do not see any gizmons inside Nuke (15.1v1) so I need to manually drag'n'drop them

**Comment by vinavfx** [comment]
You need to have liveportrail and liveportrat advanced installed in ComfyUI

**Comment by vinavfx** [comment]
i add the src_images to the list of inputs, now you should see the message that liveportrais is not installed.
you need to update "ComfyUI for Nuke"
here the link: https://github.com/PowerHouseMan/ComfyUI-AdvancedLivePortrait
Thanks for the report.
![Screenshot at 2024-09-04 21-15-08](https://github.com/user-attachments/assets/c8dcb56c-e7f6-40df-a81f-5d93f8487293)


https://github.com/vinavfx/ComfyUI-for-Nuke/commit/5c75db0e1f92316f3037c0c1b6f21b0cc74f63b0
